name: datadog-build-scan-push
'on':
  push:
    branches:
      - main
  workflow_dispatch: null
env:
  REGISTRY: ghcr.io
  AGENT_VERSION: 7.63.0
  AGENT_IMAGE_NAME: betterup/datadog-agent/datadog-agent
  CLUSTER_AGENT_IMAGE_NAME: betterup/datadog-agent/datadog-cluster-agent
jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.14
      - name: Install Python requirements
        run: |
          pip install -r requirements.txt
      - name: Setup environment variables
        run: |
          echo "CODEQL_PYTHON=$(which python3)" >> $GITHUB_ENV
          echo "$GOPATH/bin" >> $GITHUB_PATH
          echo "CGO_LDFLAGS= -L${GITHUB_WORKSPACE}/rtloader/build/rtloader -ldl " >> $GITHUB_ENV
          echo "CGO_CFLAGS= -I${GITHUB_WORKSPACE}/rtloader/include  -I${GITHUB_WORKSPACE}/rtloader/common " >> $GITHUB_ENV
      - uses: actions/setup-go@v3
        with:
          go-version-file: .go-version
      - name: Set full image names with version suffix
        run: |
          echo "AGENT_IMAGE_NAME_FULL=${{ env.REGISTRY }}/${{ env.AGENT_IMAGE_NAME }}:${{ github.sha }}-${{ env.AGENT_VERSION }}-GOV" >> $GITHUB_ENV
          echo "CLUSTER_AGENT_IMAGE_NAME_FULL=${{ env.REGISTRY }}/${{ env.CLUSTER_AGENT_IMAGE_NAME }}:${{ github.sha }}-${{ env.AGENT_VERSION }}-GOV" >> $GITHUB_ENV
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Datadog agent
        run: |
          docker pull gcr.io/datadoghq/agent:$AGENT_VERSION
          docker tag gcr.io/datadoghq/agent:$AGENT_VERSION ${{ env.AGENT_IMAGE_NAME_FULL }}
      - name: Build Datadog cluster agent
        run: |
          docker pull gcr.io/datadoghq/cluster-agent:$AGENT_VERSION
          docker tag gcr.io/datadoghq/cluster-agent:$AGENT_VERSION ${{ env.CLUSTER_AGENT_IMAGE_NAME_FULL }}
      - name: Prisma Cloud image scan agent
        id: scan-agent
        uses: PaloAltoNetworks/prisma-cloud-scan@v1
        with:
          pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
          pcc_user: ${{ secrets.PCC_USER }}
          pcc_pass: ${{ secrets.PCC_PASS }}
          image_name: ${{ env.AGENT_IMAGE_NAME_FULL }}
      - name: Prisma Cloud image scan cluster-agent
        id: scan-cluster-agent
        uses: PaloAltoNetworks/prisma-cloud-scan@v1
        with:
          pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
          pcc_user: ${{ secrets.PCC_USER }}
          pcc_pass: ${{ secrets.PCC_PASS }}
          image_name: ${{ env.CLUSTER_AGENT_IMAGE_NAME_FULL }}
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
      - name: Push agent to ghcr.io
        run: |
          docker push ${{ env.AGENT_IMAGE_NAME_FULL }}
      - name: Push cluster-agent to ghcr.io
        run: |
          docker push ${{ env.CLUSTER_AGENT_IMAGE_NAME_FULL }}
      - name: Sign agent image with a key
        run: |
          cosign sign --key env://COSIGN_PRIVATE_KEY ghcr.io/${{ env.AGENT_IMAGE_NAME_FULL }}
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      - name: Sign cluster-agent image with a key
        run: |
          cosign sign --key env://COSIGN_PRIVATE_KEY ghcr.io/${{ env.CLUSTER_AGENT_IMAGE_NAME_FULL }}
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
